
// ── Popup Definitions for unresolved related pills ──
const POPUP_DEFS = {
  '% Composition': 'Mass percentage of each element in a compound. Found by (mass of element / molar mass) × 100. Used to determine empirical formula.',
  '1,2-Diol': 'Compound with OH groups on adjacent carbons (vicinal diol). Formed by dihydroxylation of alkenes (OsO₄ or KMnO₄ cold). Undergoes pinacol rearrangement with acid.',
  '1,4-Addition': 'Conjugate addition: nucleophile adds to the β-carbon of an α,β-unsaturated carbonyl (position 4). Favoured by Gilman reagents (R₂CuLi) and soft nucleophiles.',
  '18-Electron Rule': 'Stable transition metal complexes often have 18 electrons in the valence shell (like noble gas). EAN rule equivalent. [Ni(CO)₄], [Fe(CO)₅] obey this rule.',
  '3-centre Bond': 'Three-centre two-electron (3c-2e) bond: one bonding MO shared over 3 atoms with only 2 electrons. Found in diborane B₂H₆ bridging H atoms. Electron-deficient bonding.',
  'AC Generator': 'Device converting mechanical energy to AC using electromagnetic induction. Rotating coil in magnetic field. EMF: ε = NBAω sin(ωt). Frequency determined by rotation speed.',
  'AP': 'Arithmetic Progression: sequence with constant difference d. General term: aₙ = a + (n−1)d. Sum: Sₙ = n/2(2a + (n−1)d).',
  'AP Sum Formula': 'Sum of AP: Sₙ = n/2 × (first term + last term) = n/2 × (2a + (n−1)d). Sum of first n natural numbers = n(n+1)/2.',
  'Acetoacetic Ester Synthesis': 'Synthesis of methyl ketones using ethyl acetoacetate. Alkylation at α-carbon, then hydrolysis and decarboxylation (β-keto acid) gives RCOCH₃. Chain extension by 1 carbon.',
  'Activation Energy': 'Ea: minimum energy required for a reaction to occur. From Arrhenius equation: k = Ae^(−Ea/RT). Catalyst lowers Ea. Graphically: slope of ln k vs 1/T = −Ea/R.',
  'Activity': 'A = λN = λN₀e^(−λt). Activity of a radioactive sample in decays per second (Becquerel) or disintegrations per minute. A = A₀e^(−λt). A₀/2 after one half-life.',
  'Activity Coefficient': 'γ: correction factor for non-ideal solution behaviour. For ideal solution γ = 1. Chemical potential μ = μ° + RT ln(γx). Related to Raoult\'s law deviations.',
  'Air Pollution': 'Presence of harmful substances in atmosphere. Primary pollutants (CO, NOₓ, SO₂, particulates) emitted directly. Secondary pollutants (O₃, PAN) formed by atmospheric reactions.',
  'Alcohol Classification': 'Primary (1°): RCH₂OH. Secondary (2°): R₂CHOH. Tertiary (3°): R₃COH. Distinguished by Lucas test (ZnCl₂/HCl), Victor Meyer\'s test, oxidation reactions.',
  'Aldehyde Reactions': 'Aldehydes (RCHO): nucleophilic addition (HCN, RMgX, NaBH₄), oxidation to RCOOH (Tollens, Fehling, KMnO₄), aldol condensation, Cannizzaro (no α-H), Wittig reaction.',
  'Aldehyde vs Ketone': 'Aldehydes (RCHO): reducing (Tollens+, Fehling+), oxidised to RCOOH. Ketones (R₂CO): non-reducing (Tollens−, Fehling−), resistant to mild oxidation. Both give 2,4-DNP precipitate.',
  'Alkene Reactions': 'Addition reactions of alkenes: HX (Markovnikov), H₂O (acid-cat), H₂/Pd, Br₂, HBr/ROOR (anti-Markovnikov), OsO₄/KMnO₄ (dihydroxylation), O₃ (ozonolysis), epoxidation (mCPBA).',
  'Alkene Stability': 'More substituted alkene more stable (hyperconjugation). Order: tetrasubstituted > trisubstituted > disubstituted > monosubstituted > ethylene. Trans > cis (less steric strain).',
  'Alkoxide': 'RO⁻: formed from R-OH + Na/NaH/NaNH₂. Strong base and nucleophile. Used in Williamson synthesis (SN2 on RX → ether), and elimination (E2).',
  'Alkylation': 'Introduction of alkyl group into molecule. Carbon alkylation: enolate + RX (SN2). Friedel-Crafts alkylation: ArH + RX/AlCl₃ → ArR. Acetylide + RX → chain elongation.',
  'Amide Reactions': 'Amide (RCONH₂): hydrolysis (acid/base → RCOOH + NH₃), reduction (LiAlH₄ → amine), Hofmann bromamide (Br₂/NaOH → RNH₂, chain shortened), dehydration → nitrile.',
  'Amine Classification': 'Primary (RNH₂), secondary (R₂NH), tertiary (R₃N). Distinguished by Hinsberg test (benzenesulfonyl chloride). Also by nitrous acid: 1°→diazonium, 2°→nitrosamine, 3°→no reaction.',
  'Amine Reactions': 'Amines: alkylation, acylation (→amide), reaction with HNO₂ (depends on class), Schiff base formation (1° + RCHO), electrophilic substitution (ArNH₂ activated ring).',
  'Amine Synthesis': 'Methods: Gabriel synthesis (1° only), reduction of nitro/nitrile/amide (LiAlH₄), Hofmann bromamide (RCONH₂ → RNH₂), reductive amination (RCHO + NH₃ + H₂), Curtius/Schmidt rearrangements.',
  'Amino Acid Synthesis': 'Strecker synthesis: RCHO + NH₃ + HCN → α-aminonitrile → hydrolysis → α-amino acid. HVZ reaction: α-bromo acid + NH₃. Gabriel-malonic ester method.',
  'Amino Acids': 'Building blocks of proteins. α-amino acids: NH₂ and COOH on same carbon. 20 natural L-amino acids. Zwitterionic at isoelectric point (pI). Peptide bond: −CO−NH−.',
  'Amphoteric Oxides': 'Oxides reacting with both acids and bases. Al₂O₃, ZnO, SnO, PbO, Cr₂O₃, MnO₂. Al₂O₃ + NaOH → NaAlO₂ + H₂O; Al₂O₃ + HCl → AlCl₃ + H₂O.',
  'Angle Between Vectors': 'cos θ = (a⃗·b⃗)/(|a⃗||b⃗|). For lines in 3D: use direction cosines. Lines perpendicular if a⃗·b⃗ = 0. Lines parallel if a⃗×b⃗ = 0⃗.',
  'Angle Bisector': 'Locus of points equidistant from two lines. For ax+by+c=0 and a\'x+b\'y+c\'=0: (ax+by+c)/√(a²+b²) = ±(a\'x+b\'y+c\')/√(a\'²+b\'²). One bisector is acute, other obtuse.',
  'Angular Impulse': 'L = τ·t (for constant torque). More generally: ΔL = ∫τ dt. Analogous to linear impulse J = Δp. Units: kg·m²/s or N·m·s.',
  'Angular Momentum': 'L⃗ = r⃗×p⃗ = Iω⃗. For circular motion: L = mvr. Conservation: when net torque = 0, L is constant. Used in: planetary motion, figure skater, gyroscope.',
  'Aniline Synthesis': 'Reduction of nitrobenzene: Zn/HCl, Fe/HCl, or H₂/Pd → aniline. Hofmann degradation of benzamide. Ammonolysis of chlorobenzene (Dow process, harsh conditions).',
  'Anomalous Properties of Li': 'Li resembles Mg (diagonal relationship): forms normal oxide (not peroxide), reacts slowly with water, forms Li₃N with N₂, Li₂CO₃ insoluble, LiOH weakest group 1 hydroxide.',
  'Applications of Derivatives': 'Tangent/normal, rate of change, monotonicity (increasing/decreasing intervals), maxima/minima, concavity, curve sketching, L\'Hôpital\'s rule, approximation using differentials.',
  'Aromatic Chemistry': 'Chemistry of benzene and related compounds. Electrophilic aromatic substitution (EAS): nitration, halogenation, sulfonation, Friedel-Crafts. Stability from aromaticity (6π electrons).',
  'Aromaticity': 'Cyclic, planar, fully conjugated, (4n+2)π electrons (Hückel). Benzene (6π), naphthalene (10π). Aromatic compounds unusually stable. Undergo substitution, not addition.',
  'Asymptotes': 'Lines approached by a curve but never crossed. For hyperbola x²/a²−y²/b²=1: y = ±(b/a)x. Rectangular hyperbola xy = c²: x and y axes. Oblique asymptotes for rational functions.',
  'Atmospheric Chemistry': 'Chemical reactions in atmosphere. Troposphere: smog, ozone from NOₓ/VOC/UV. Stratosphere: ozone layer (O₃ absorbs UV-B). Ozone depletion by CFCs (Cl• chain reaction).',
  'Aufbau Principle': 'Electrons fill orbitals in order of increasing energy: 1s<2s<2p<3s<3p<4s<3d<4p... (n+l rule, then lower n first). Combined with Pauli exclusion and Hund\'s rule.',
  'Azo Dyes': 'Compounds containing −N=N− (azo) chromophore. Made by coupling diazonium salt with activated ring (phenol/amine). Examples: methyl orange, Congo red, butter yellow. Largest class of dyes.',
  'BOD': 'Biological Oxygen Demand: O₂ consumed by microbes to decompose organic matter in 5 days at 20°C. Clean water: <1 mg/L; polluted: >5 mg/L. High BOD depletes dissolved O₂, killing fish.',
  'Balancing Equations': 'Methods: (1) Hit-and-trial. (2) Oxidation number: balance OS change. (3) Half-reaction (ion-electron) method: balance each half-reaction then combine. Always verify atom and charge balance.',
  'Basis Vectors': 'Set of linearly independent vectors that span the space. Standard basis in 3D: î, ĵ, k̂. Any vector expressible as unique linear combination. For n-dimensional space, need n basis vectors.',
  'Bayer Process': 'Extraction of Al₂O₃ from bauxite using NaOH. Al₂O₃ + 2NaOH → 2NaAlO₂ + H₂O (dissolves Al, leaves Fe₂O₃). Precipitate Al(OH)₃ by seeding → calcine → pure Al₂O₃.',
  'Binary Representation': 'Numbers in base 2 using 0 and 1. Connected to subsets: each element in/out → binary digit. Number of subsets of n-element set = 2ⁿ (n binary digits, 2 choices each).',
  'Biomagnification': 'Concentration of pollutant increases up food chain. DDT, mercury, PCBs. 10× increase at each trophic level. Apex predators (eagles, humans) most affected. Also called bioaccumulation.',
  'Biomolecules': 'Molecules found in living organisms. Carbohydrates (CₙH₂ₙOₙ), proteins (amino acid polymers), lipids (fats/oils), nucleic acids (DNA, RNA). All contain C, H, O and usually N.',
  'Bleaching': 'Decolorizing by oxidation (Cl₂, O₃, H₂O₂, bleaching powder) or reduction (SO₂, Na₂S₂O₄). SO₂ bleaching is reversible. Oxidative bleaching is permanent. Used for textiles, paper, flour.',
  'Bleaching Agents': 'Oxidising: Cl₂, bleaching powder (CaOCl₂), NaOCl, H₂O₂, O₃, KMnO₄. Reducing: SO₂, Na₂S₂O₄ (sodium hydrosulphite). Bleaching powder: Ca(OCl)Cl, releases HOCl in water.',
  'Boiling Point Elevation': 'ΔTb = Kb·m·i. Kb = ebullioscopic constant (water: 0.512 K·kg/mol). Colligative property. Solute elevates bp by preventing vapour pressure reaching external pressure at normal bp.',
  'Born-Haber Cycle': 'Thermodynamic cycle applying Hess\'s law to calculate lattice energy. Steps: sublimation, dissociation, ionisation, electron affinity, lattice energy. Sum = ΔHf° (Hess\'s law).',
  'Brownian Motion': 'Random zigzag motion of colloidal particles due to bombardment by solvent molecules. Demonstrates kinetic energy of solvent. Intensity increases with temperature, decreases with particle size.',
  'Carbanion Stability': 'Order: CH₃⁻ > 1° > 2° > 3° (opposite to carbocations). Stabilised by −I groups (CF₃, CN), sp hybridisation (acetylide most stable), resonance (allylic/benzylic). Basis for acidity order.',
  'Carbene': 'Highly reactive intermediate with divalent carbon (:CR₂). Generated from CHX₃ + base (dichlorocarbene :CCl₂). Singlet and triplet forms. Inserts into C−H bonds, adds to alkenes → cyclopropane.',
  'Catalysis': 'Increases reaction rate by lowering activation energy without being consumed. Homogeneous (same phase) vs heterogeneous (different phase). Catalyst provides alternate mechanism. ΔG unchanged.',
  'Centroid': 'Point dividing medians in 2:1 ratio. For triangle with vertices (x₁,y₁), (x₂,y₂), (x₃,y₃): G = ((x₁+x₂+x₃)/3, (y₁+y₂+y₃)/3). Also centre of mass for uniform triangular lamina.',
  'Chain Reactions': 'Self-propagating reactions with initiation, propagation, termination. Each propagation step produces a reactive species (radical) that sustains the chain. Nuclear fission and combustion are examples.',
  'Chain Rule': 'd/dx[f(g(x))] = f\'(g(x))·g\'(x). For composite functions. Extension: d/dt[f(x(t), y(t))] = (∂f/∂x)(dx/dt) + (∂f/∂y)(dy/dt). Used for implicit and parametric differentiation.',
  'Characteristic Equation': 'det(A − λI) = 0. Polynomial equation in λ whose roots are eigenvalues. Cayley-Hamilton: every matrix satisfies its own characteristic equation (A² − tr(A)A + det(A)I = 0 for 2×2).',
  'Characteristic Polynomial': 'p(λ) = det(A − λI). For 2×2: λ² − tr(A)λ + det(A). Roots are eigenvalues. Degree = order of matrix. Used in Cayley-Hamilton theorem.',
  'Chelation': 'Formation of multiple bonds from a single ligand to a metal ion (chelate = claw). Bidentate (en, oxalate), tridentate, EDTA (hexadentate). Chelate effect: greater stability due to entropy gain.',
  'Chord of Contact': 'For circle x²+y²=a²: chord of contact from external point (x₁,y₁) is xx₁+yy₁=a². For parabola y²=4ax from (h,k): ky = 2a(x+h). Line joining points of tangency.',
  'Chromophores': 'Structural unit responsible for colour in organic compounds. Examples: −N=N− (azo), C=O (carbonyl), C=C−C=C (conjugated). Absorbs specific visible wavelength; complementary colour observed.',
  'Circular Motion': 'Object moving in circle. Centripetal acceleration a = v²/r = ω²r. Centripetal force F = mv²/r. Angular velocity ω = v/r. Period T = 2π/ω. For vertical circle: minimum speed at top = √(gr).',
  'Circumradius': 'R = abc/4Δ = a/2sinA. For equilateral triangle: R = a/√3. Distance from circumcentre to each vertex. Related to sine rule: a/sinA = 2R.',
  'Close Packing': 'Arrangement of spheres to maximise packing efficiency. HCP (hexagonal close packing) and CCP/FCC (cubic close packing): both 74% efficiency, 12 nearest neighbours (coordination number).',
  'Coefficient of Variation': 'CV = (σ/μ) × 100%. Relative measure of dispersion. Dimensionless. Useful for comparing variability of datasets with different units or means. Lower CV = more consistent.',
  'Coherence': 'Two sources are coherent if they maintain constant phase difference. Required for stable interference pattern. LASER light is highly coherent. Two independent sources are incoherent.',
  'Colligative Properties': 'Properties depending on number of solute particles, not nature: VP lowering, boiling point elevation, freezing point depression, osmotic pressure. Modified by van\'t Hoff factor i for electrolytes.',
  'Collinearity': 'Three points A, B, C are collinear if area of triangle = 0, i.e., |x₁(y₂−y₃)+x₂(y₃−y₁)+x₃(y₁−y₂)| = 0. Also if slope AB = slope BC. In 3D: (B−A)×(C−A) = 0⃗.',
  'Color Wheel': 'Complementary colours are opposite on wheel. A complex absorbing 400-450nm (violet) appears yellow-green. Absorbing 490nm (blue-green) appears red-orange. Used to predict colour of coordination complexes.',
  'Color of Complexes': 'd-d electronic transition: electron absorbs photon to jump from t₂g to eₘ. Energy gap Δ = hf corresponds to absorbed wavelength. Observed colour = complementary of absorbed. Colourless if d⁰ or d¹⁰.',
  'Combination of Errors': 'For Z = A + B or Z = A − B: ΔZ = ΔA + ΔB (errors add). For Z = AB or Z = A/B: ΔZ/Z = ΔA/A + ΔB/B. For Z = Aⁿ: ΔZ/Z = n·ΔA/A.',
  'Combinations': 'C(n,r) = n!/[r!(n−r)!]. Number of ways to choose r items from n without regard to order. C(n,r) = C(n,n−r). Sum of all: 2ⁿ. Pascal\'s identity: C(n,r) = C(n−1,r−1) + C(n−1,r).',
  'Combinatorics': 'Branch of mathematics counting, arranging, and selecting objects. Includes permutations, combinations, pigeonhole principle, inclusion-exclusion, generating functions.',
  'Compressibility Factor': 'Z = PV/nRT. Ideal gas: Z = 1 always. Real gas: Z < 1 (dominant attractions, low P) or Z > 1 (dominant repulsions, high P). At Boyle temperature, Z ≈ 1 over wide P range.',
  'Compressibility Factor Z': 'Z = PV/nRT. Measures deviation from ideal gas behaviour. Z < 1: intermolecular attractions dominant. Z > 1: repulsions dominant. At high T and low P, Z → 1 for all gases.',
  'Compton Effect': 'X-ray photon collides with free electron; scattered photon has longer wavelength. Δλ = (h/mₑc)(1−cosθ). Demonstrates particle nature of light. Compton shift independent of wavelength.',
  'Condensation Polymers': 'Formed by step-growth polymerisation releasing small molecules (H₂O, HCl). Examples: nylon (amide bonds), polyester (ester bonds), Bakelite (phenol-formaldehyde), cellulose.',
  'Conformational Analysis': 'A concept related to Conformational Analysis. Refer to your textbook for the specific formula or definition.',
  'Conjugation': 'System of alternating single and double (or triple) bonds. Extends π-electron delocalisation. Increases stability (lower energy). Bathochromic shift in UV-Vis (lower HOMO-LUMO gap). Key in dyes.',
  'Conservation of Angular Momentum': 'L⃗_total = constant when net external torque = 0. Examples: figure skater pulling arms in (ω increases), planet speed in elliptical orbit, gyroscope stability.',
  'Coordination Number': 'Number of ligand atoms directly bonded to central metal. Common: 4 (tetrahedral/square planar), 6 (octahedral). Radius ratio predicts CN for ionic solids. Affects crystal field splitting.',
  'Coplanarity': 'Four points coplanar if scalar triple product of three edge vectors = 0. Three vectors coplanar if [a b c] = 0. All vectors in 2D are coplanar.',
  'Copolymers': 'A concept related to Copolymers. Refer to your textbook for the specific formula or definition.',
  'Counting Relations': 'A concept related to Counting Relations. Refer to your textbook for the specific formula or definition.',
  'Covariance': 'A concept related to Covariance. Refer to your textbook for the specific formula or definition.',
  'Critical Constants': 'Tc = 8a/27Rb, Pc = a/27b², Vc = 3nb (from van der Waals). Above critical temperature, gas cannot be liquefied regardless of pressure. CO₂: Tc = 304.2 K, Pc = 73.8 atm.',
  'Critical Points': 'A concept related to Critical Points. Refer to your textbook for the specific formula or definition.',
  'Cubic Equations': 'ax³+bx²+cx+d=0. Sum of roots = −b/a, sum of products of pairs = c/a, product = −d/a (Vieta\'s). Discriminant determines nature of roots. Cardano\'s formula for general solution.',
  'Curtius Rearrangement': 'Acyl azide (RCONₓ₃) → isocyanate (RNCO) on heating → hydrolysis → primary amine (chain shortened by 1C). Similar to Hofmann but from acyl azide. Used when Hofmann conditions too harsh.',
  'Curve Sketching': 'Steps: domain, intercepts, symmetry (even/odd), asymptotes, critical points (f\'=0), intervals of increase/decrease, inflection points (f\'\'=0), concavity. Then sketch.',
  'Cyclotron': 'Particle accelerator using magnetic field (circular motion) and alternating electric field (acceleration at each gap). Radius r = mv/qB increases with speed. Cyclotron frequency f = qB/2πm (independent of v).',
  'DBE': 'Degree of unsaturation = (2C+2+N−H−X)/2. Each π bond or ring = 1 DBE. Benzene = 4 DBE. Used to determine degree of unsaturation from molecular formula before elucidating structure.',
  'Damped Oscillations': 'A concept related to Damped Oscillations. Refer to your textbook for the specific formula or definition.',
  'Deficiency Diseases': 'Vitamin A: night blindness. D: rickets. B₁: beri-beri. B₁₂: pernicious anaemia. C: scurvy. K: clotting defect. Protein deficiency: kwashiorkor (oedema), marasmus (wasting).',
  'Diastereomers': 'Stereoisomers that are NOT mirror images. Have different physical properties. Differ in configuration at one or more (but not all) stereocentres. Include cis/trans isomers. Separable by chromatography.',
  'Dielectric': 'Insulating material placed between capacitor plates. Increases capacitance: C = KC₀ (K = dielectric constant). Reduces electric field: E = E₀/K. Polar dielectrics: dipoles align. Non-polar: induced dipoles.',
  'Diffraction Grating': 'Multiple slits with spacing d. Condition for maxima: nλ = d sinθ. Resolving power = nN (n = order, N = number of slits). Much higher resolution than single slit.',
  'Dilution Formula': 'M₁V₁ = M₂V₂. Moles of solute conserved on dilution. Also N₁V₁ = N₂V₂ for normality. Adding solvent increases volume but doesn\'t change moles of solute.',
  'Directive Effects': 'A concept related to Directive Effects. Refer to your textbook for the specific formula or definition.',
  'Disinfection': 'Killing pathogens in water. Chlorination (HOCl), UV radiation, ozone (most effective, no residual taste), boiling, chloramine (more stable than Cl₂). Residual disinfectant prevents recontamination.',
  'Dispersion': 'Separation of white light into colours due to wavelength-dependent refractive index. n(violet) > n(red). Dispersive power ω = (nv−nr)/(ny−1). Rainbow formed by dispersion and TIR in water droplets.',
  'Disproportionation': 'Redox reaction where same element is simultaneously oxidised and reduced. Example: 2H₂O₂ → 2H₂O + O₂ (O: −1→−2 and −1→0). Cu: 2Cu⁺ → Cu + Cu²⁺. H₂O₂ and Cu⁺ prone to disproportionation.',
  'Dissolved Oxygen': 'DO: O₂ dissolved in water (ppm). Healthy water: 8-10 ppm. Fish need >5 ppm. Decreases with temperature and pollution (BOD). Low DO = eutrophication and dead zones.',
  'E1 and E2': 'A concept related to E1 and E2. Refer to your textbook for the specific formula or definition.',
  'E1/E2': 'A concept related to E1/E2. Refer to your textbook for the specific formula or definition.',
  'EAN Rule': 'Effective Atomic Number = metal electrons + electrons from ligands = 36, 54, or 86 (noble gas). Most carbonyl complexes obey. [Ni(CO)₄]: 28 + 8 = 36. Equivalent to 18-electron rule.',
  'EAS': 'Electrophilic Aromatic Substitution. Mechanism: electrophile attacks π cloud → σ-complex (arenium ion) → proton loss restores aromaticity. Rate-determining = electrophile attack step.',
  'EAS Mechanism': 'Step 1: E⁺ generated (NO₂⁺, Cl⁺ via catalyst, etc.). Step 2: E⁺ attacks ring → arenium ion (Wheland intermediate). Step 3: H⁺ lost → aromatic product. ortho/para direction by +M groups.',
  'EAS and NAS': 'EAS (electrophilic aromatic substitution) for electron-rich rings. NAS (nucleophilic aromatic substitution) for electron-poor rings (many −NO₂ groups). NAS requires activated ring and good leaving group.',
  'EAS on Phenol': 'Phenol (PhOH) very reactive in EAS due to +M effect of −OH. ortho and para activated. Even reacts with Br₂ without catalyst (tribromophenol precipitate). Diazonium coupling also occurs at ortho/para.',
  'EMF and Internal Resistance': 'ε = V + Ir where V = terminal voltage, I = current, r = internal resistance. Terminal voltage drops under load. Short circuit current: I_sc = ε/r. Maximum power transfer: R_ext = r.',
  'Eccentric Angle': 'A concept related to Eccentric Angle. Refer to your textbook for the specific formula or definition.',
  'Elastomers': 'Polymers that can be stretched and return to original shape (elastic). Natural rubber (cis-polyisoprene), neoprene (polychloroprene), Buna-S (SBR), silicone rubber. Require vulcanisation for practical use.',
  'Emulsification': 'Dispersion of one immiscible liquid in another as droplets. Requires emulsifier (surfactant) to stabilise. O/W (oil-in-water): milk, cream. W/O (water-in-oil): butter, margarine.',
  'Energy in SHM': 'A concept related to Energy in SHM. Refer to your textbook for the specific formula or definition.',
  'Enolate': 'A concept related to Enolate. Refer to your textbook for the specific formula or definition.',
  'Enthalpy': 'H = U + PV. At constant pressure: ΔH = qₚ. ΔH = ΔU + Δnₘ RT for gaseous reactions. Bond enthalpies, formation enthalpies, Hess\'s law all use ΔH.',
  'Equilibrium Constant': 'K_eq (or K_c) = [products]/[reactants] at equilibrium. Relates to ΔG°: ΔG° = −RT ln K. Large K (>10³): product-favoured. Small K (<10⁻³): reactant-favoured. Temperature-dependent.',
  'Ether Synthesis': 'Williamson synthesis (NaOR + RX, SN2). Acid-catalysed dehydration of alcohols (2 ROH → R₂O + H₂O). Grignard + epoxide. Industrial: diethyl ether from ethanol + H₂SO₄ at 140°C.',
  'Even/Odd Functions': 'Even: f(−x) = f(x), symmetric about y-axis. Odd: f(−x) = −f(x), symmetric about origin. ∫₋ₐᵃ f(x)dx = 2∫₀ᵃf(x)dx (even); = 0 (odd). Every function = even part + odd part.',
  'Exponential Distribution': 'P(X>t) = e^(−λt). Memoryless continuous distribution. Mean = 1/λ, Variance = 1/λ². Continuous analogue of geometric distribution. Models waiting time between Poisson events.',
  'Exponential Functions': 'f(x) = aˣ, domain all reals, range (0,∞). d/dx(eˣ) = eˣ. Inverse of logarithm. e ≈ 2.718. Exponential growth/decay models: N = N₀eˏt or N₀e^(−λt).',
  'Extraction of Metals': 'A concept related to Extraction of Metals. Refer to your textbook for the specific formula or definition.',
  'Extrema Problems': 'A concept related to Extrema Problems. Refer to your textbook for the specific formula or definition.',
  'FTC': 'Fundamental Theorem of Calculus. Part 1: d/dx ∫ₐˣf(t)dt = f(x). Part 2: ∫ₐᵇf(x)dx = F(b) − F(a) where F\'= f. Links differentiation and integration as inverse operations.',
  'Fajan\'s Rules': 'Conditions for covalent character in ionic compounds: high charge/small cation (high polarising power) + large/highly charged anion (high polarisability). Small Be²⁺ and Al³⁺ highly polarising.',
  'Fehling\'s Test': 'Cu²⁺ (in tartrate complex, deep blue) reduced by aldehyde to Cu₂O (brick-red precipitate). Positive: aldehydes, glucose, fructose (via ring opening). Negative: ketones (except α-hydroxy ketones).',
  'Freundlich Isotherm': 'A concept related to Freundlich Isotherm. Refer to your textbook for the specific formula or definition.',
  'Friction Force': 'f = μN. Static: 0 ≤ f_s ≤ μ_s N. Kinetic: f_k = μ_k N (< μ_s N). Angle of friction λ: tan λ = μ. Angle of repose = angle of friction. Rolling friction < sliding friction.',
  'Functional Groups': 'Atoms/groups determining reactivity: −OH (alcohol/phenol), −COOH (acid), −CHO (aldehyde), −CO− (ketone), −NH₂ (amine), −X (halide), −CN (nitrile), −COOR (ester), −CONH₂ (amide).',
  'GP': 'Geometric Progression: sequence where each term = previous × constant ratio r. General term: aₙ = arⁿ⁻¹. Geometric mean GM = √(ab). Product of n terms = (first × last)^(n/2).',
  'GP Sum Formula': 'Sum of GP: Sₙ = a(rⁿ−1)/(r−1) for r ≠ 1. Sum to infinity: S∞ = a/(1−r) for |r| < 1. Geometric mean of a and b is √(ab).',
  'Gamma Function': 'Γ(n) = (n−1)! for positive integers. Γ(1/2) = √π. Extension of factorial to real/complex numbers. Appears in reduction formula: Γ(n+1) = nΓ(n). Used in advanced integration.',
  'Genetic Code': 'Triplet codons (3 bases) code for amino acids. 64 codons for 20 amino acids (degenerate code). AUG: start codon (methionine). UAA, UAG, UGA: stop codons. Codon on mRNA, anticodon on tRNA.',
  'Glycosidic Bond': 'Bond between anomeric carbon (C1) of sugar and another molecule (−OH of another sugar or alcohol). α or β linkage depending on configuration at C1. Sucrose: α-1,2-glycosidic bond.',
  'Graham\'s Law': 'Rate of diffusion ∝ 1/√M. r₁/r₂ = √(M₂/M₁). At same T and P, lighter gas diffuses faster. Used for isotope separation (UF₆ enrichment). Effusion (through pinhole) follows same law.',
  'Gravitational Field': 'A concept related to Gravitational Field. Refer to your textbook for the specific formula or definition.',
  'Gravitational Potential': 'A concept related to Gravitational Potential. Refer to your textbook for the specific formula or definition.',
  'Half-Life': 'Time for half the radioactive nuclei to decay. t½ = 0.693/λ. After n half-lives: N = N₀/2ⁿ. First-order reactions also have half-life independent of initial concentration.',
  'Hall Effect': 'Transverse voltage in current-carrying conductor placed in perpendicular magnetic field. Hall voltage V_H = IB/ned. Determines carrier type (sign of V_H) and carrier concentration. Hall coefficient R_H = 1/ne.',
  'Haloacids': 'Acidity of HF < HCl < HBr < HI (bond strength decreases down group, weaker bond → more acidic). In water: HF weak acid (HF₂⁻ formation), HCl/HBr/HI strong acids.',
  'Halogenation at α-C': 'A concept related to Halogenation at α-C. Refer to your textbook for the specific formula or definition.',
  'Halogens': 'A concept related to Halogens. Refer to your textbook for the specific formula or definition.',
  'Heat Capacity': 'C = dQ/dT. Molar heat capacity for ideal gas: Cᵥ (monoatomic) = 3/2 R, Cₚ = 5/2 R. Diatomic: Cᵥ = 5/2 R, Cₚ = 7/2 R. Always: Cₚ − Cᵥ = R for ideal gas.',
  'Heat Engine': 'Device converting heat to work. Efficiency η = W/Q_H = 1 − Q_C/Q_H. For Carnot: η = 1 − T_C/T_H. No engine can have η > Carnot efficiency (second law).',
  'Heron\'s Formula': 'Area Δ = √(s(s−a)(s−b)(s−c)) where s = (a+b+c)/2. No angle needed. Used with inradius formula r = Δ/s and circumradius R = abc/4Δ.',
  'Hess\'s Law': 'ΔH of reaction is independent of path (state function). ΔH_rxn = ΣΔH_f(products) − ΣΔH_f(reactants). Can add/subtract equations and their ΔH values.',
  'Higher Order Derivatives': 'f\'\'(x) = d²y/dx². Second derivative: concavity, acceleration. nth derivative notation: f^(n)(x) = dⁿy/dxⁿ. Leibniz rule for nth derivative of product: (uv)⁽ⁿ⁾ = Σ C(n,k) u⁽ᵏ⁾v⁽ⁿ⁻ᵏ⁾.',
  'Homogeneous ODE': 'dy/dx = f(y/x). Solved by substitution y = vx → separable equation. Linear homogeneous: dy/dx + P(x)y = 0. Solution by integrating factor e^(∫Pdx).',
  'Identification Tests': 'Tollens\' (silver mirror): aldehyde. Fehling\'s (brick-red): reducing sugar/aldehyde. Iodoform (yellow): CH₃CO−R. Lucas (turbidity): 3° > 2° > 1° alcohol. Hinsberg: amine class.',
  'Implicit Differentiation': 'Differentiate both sides of F(x,y)=0 w.r.t. x, treating y as function of x. dy/dx = −(∂F/∂x)/(∂F/∂y). Used when y cannot be expressed explicitly as function of x.',
  'Impulse-Momentum': 'J = FΔt = Δp = m(v−u). Impulse = area under F−t graph. Conservation: if J_external = 0, momentum conserved. Used in collision and explosion problems.',
  'Independence': 'Events A, B independent if P(A∩B) = P(A)·P(B). Equivalently P(A|B) = P(A). Random variables X, Y independent if joint probability = product of marginals. For n events, check all subsets.',
  'Industrial Chemistry': 'Large-scale chemical production. Haber process: N₂+3H₂→2NH₃ (Fe catalyst, 450°C, 200 atm). Contact process: SO₂+½O₂→SO₃ (V₂O₅ catalyst). Solvay process: Na₂CO₃ from NaCl.',
  'Industrial Organic Chemistry': 'A concept related to Industrial Organic Chemistry. Refer to your textbook for the specific formula or definition.',
  'Inequalities': 'A concept related to Inequalities. Refer to your textbook for the specific formula or definition.',
  'Inert Pair Effect': 'Tendency of outermost s electrons (6s² in 6th period) to remain paired and not participate in bonding. Causes lower oxidation state stability: Pb²⁺>Pb⁴⁺, Bi³⁺>Bi⁵⁺, Tl⁺>Tl³⁺.',
  'Infinite Series': 'Sum of infinitely many terms. Convergent if sum approaches finite limit. Geometric: S∞ = a/(1−r), |r|<1. Power series, Taylor series are infinite series. Tests: ratio, root, integral, comparison.',
  'Initial Value Problems': 'ODE with specified value of y at specific x (initial condition). y\'= f(x,y), y(x₀) = y₀. Solved by integrating ODE then applying condition to find constant. Existence and uniqueness theorem.',
  'Inradius': 'r = Δ/s (Δ = area, s = semiperimeter). Also r = 4R·sin(A/2)·sin(B/2)·sin(C/2). Centre of inscribed circle. Excircle radii: r₁ = Δ/(s−a).',
  'Intensity': 'A concept related to Intensity. Refer to your textbook for the specific formula or definition.',
  'Interhalogen Compounds': 'Compounds of two different halogens. Formula XYₙ where n = 1,3,5,7 (odd). ClF, BrF₃, IF₅, IF₇. Central atom is the larger/less electronegative halogen. VSEPR gives shape.',
  'Ion Exchange': 'Removal of ions using synthetic resin with exchangeable H⁺ or OH⁻ ions. Cation exchange: Ca²⁺ → 2H⁺ (softening). Anion exchange: Cl⁻ → OH⁻. Both together: demineralisation.',
  'Ionic Bonding': 'Transfer of electrons from metal to non-metal → electrostatic attraction between oppositely charged ions. Strong in ionic crystals. Lattice energy: large Z, small r → strong bonds. NaCl, MgO.',
  'Ionic Radii': 'Size of ion. Cations smaller than parent atom; anions larger. For isoelectronic species: higher Z → smaller radius. Used in Fajan\'s rules, radius ratio rules for crystal structure prediction.',
  'Ionic Radius': 'A concept related to Ionic Radius. Refer to your textbook for the specific formula or definition.',
  'Ionic Stability': 'Ionic compounds stable due to lattice energy. Large lattice energy = thermodynamically stable. Na₂O₂ (peroxide) and KO₂ (superoxide) stable due to size matching of large cations with large anions.',
  'Isothermal Process': 'Constant temperature process. Ideal gas: ΔU = 0. Work done W = nRT ln(V₂/V₁). Reversible isothermal gives maximum work. P₁V₁ = P₂V₂ (Boyle\'s law). Flat on T-V diagram.',
  'KMnO₄ Oxidation': 'Acidic KMnO₄ (hot, conc.): strongest oxidant. Alkene → diol → ketone/acid (cleavage). Primary alcohol → acid. Secondary → ketone. Tertiary: no reaction. Cold, dilute KMnO₄ (Baeyer reagent): gives diol (cis).',
  'Ka and Kb': 'Ka = acid dissociation constant; Kb = base dissociation constant. Ka × Kb = Kw = 10⁻¹⁴ (at 25°C). pKa + pKb = 14. Larger Ka → stronger acid. Henderson-Hasselbalch uses pKa.',
  'Kc and Kp': 'Kc = [products]^c[reactants]^d... equilibrium expression. Kp uses partial pressures. Kp = Kc(RT)^Δn where Δn = moles gas products − moles gas reactants. Both are temperature-dependent.',
  'Ksp': 'Solubility product. For MₘXₙ: Ksp = [M]^m[X]^n. Solubility s: for MX, s=√Ksp; for MX₂, s=(Ksp/4)^(1/3). Common ion decreases s. If ionic product > Ksp, precipitation occurs.',
  'Kw': 'Ionic product of water: Kw = [H⁺][OH⁻] = 10⁻¹⁴ at 25°C. Increases with temperature. At 37°C: Kw ≈ 2.5×10⁻¹⁴. Neutral solution: [H⁺] = [OH⁻] = √Kw → pH = 7 only at 25°C.',
  'L\'Hopital\'s Rule': 'If lim f/g = 0/0 or ∞/∞, then lim f/g = lim f\'/g\'. Apply repeatedly if needed. Valid for x→a, x→∞, etc. Doesn\'t work for other indeterminate forms directly.',
  'LC Oscillations': 'Inductor-capacitor circuit oscillates. Angular frequency ω₀ = 1/√(LC). Energy oscillates between electric (capacitor) and magnetic (inductor). Analogous to SHM. Damped by resistance.',
  'Lactone Formation': 'A concept related to Lactone Formation. Refer to your textbook for the specific formula or definition.',
  'Leaching': 'Selective dissolution of ore by acid, base, or cyanide solution. Au: NaCN/O₂ → [Au(CN)₂]⁻. Al₂O₃: NaOH → NaAlO₂ (Bayer process). Then precipitate/electrolyse to get metal.',
  'Leaving Group': 'A concept related to Leaving Group. Refer to your textbook for the specific formula or definition.',
  'Leaving Group Ability': 'A concept related to Leaving Group Ability. Refer to your textbook for the specific formula or definition.',
  'Lewis Acid': 'Electron pair acceptor (Lewis). BF₃, AlCl₃, Fe³⁺, Cu²⁺, H⁺. Lewis acid-base reaction: Lewis acid + base → adduct (coordinate bond). More general than Brønsted-Lowry definition.',
  'Lewis Structure': 'Dot structure showing valence electrons and bonding. Steps: count valence electrons, draw skeleton, distribute electrons for octets (exceptions: H needs 2, B 6, P/S can expand). Formal charge check.',
  'LiAlH₄ Reactions': 'A concept related to LiAlH₄ Reactions. Refer to your textbook for the specific formula or definition.',
  'Ligand Types': 'A concept related to Ligand Types. Refer to your textbook for the specific formula or definition.',
  'Lindlar Catalyst': 'Pd deposited on CaCO₃, poisoned with quinoline/lead acetate. Partially deactivated Pd: allows partial hydrogenation of alkynes to cis-alkenes. RC≡CR + H₂/Lindlar → cis-RCH=CHR.',
  'Line in 3D': 'A concept related to Line in 3D. Refer to your textbook for the specific formula or definition.',
  'Lossen Rearrangement': 'Hydroxamic acid (RCONHOH) activated by acylation/sulfonylation → rearrangement → isocyanate → hydrolysis → amine. Similar to Hofmann but from hydroxamic acid, not amide.',
  'Magnification': 'm = image size / object size = v/u (lens) = −v/u (mirror). >1: magnified; <1: diminished; negative: inverted. Angular magnification of telescope = fo/fe. Microscope m = (L/fo)(D/fe).',
  'Malonic Ester Synthesis': 'A concept related to Malonic Ester Synthesis. Refer to your textbook for the specific formula or definition.',
  'Mean Free Path': 'Average distance between collisions. λ = 1/(√2 πd²n) where d = diameter, n = number density. Increases with T (faster molecules traverse gap), decreases with P. Important in vacuum technology.',
  'Mean Value Theorem': 'If f continuous on [a,b] and differentiable on (a,b), ∃c∈(a,b): f\'(c) = (f(b)−f(a))/(b−a). Geometric: tangent somewhere parallel to chord. Rolle\'s is special case (f(a)=f(b)).',
  'Mean Variance': 'A concept related to Mean Variance. Refer to your textbook for the specific formula or definition.',
  'Meso Compounds': 'Compounds with stereocentres but with internal plane of symmetry → achiral overall. Superimposable on mirror image. Optical activity = 0. Example: meso-tartaric acid.',
  'Methyl Ketones': 'A concept related to Methyl Ketones. Refer to your textbook for the specific formula or definition.',
  'Micelles': 'Aggregates of surfactant molecules in aqueous solution above CMC. Hydrophobic tails inside, hydrophilic heads outside. Trap grease in hydrophobic core. Typical size: 5-100 nm (colloidal range).',
  'Michael Addition': '1,4-addition of stabilised carbanion (Michael donor: malonate, acetoacetate) to α,β-unsaturated carbonyl (Michael acceptor). Key C-C bond forming reaction. Robinson annulation = Michael + aldol.',
  'Microscope': 'Compound microscope: objective (short fo, high power) + eyepiece. m = (L/fo)(D/fe). Limit of resolution = λ/2μsinθ. Electron microscope uses de Broglie wavelength of electrons (much smaller).',
  'Migration': 'In carbocation/radical rearrangements: 1,2-shift of H, alkyl, or aryl group with its bonding electrons to adjacent electron-deficient centre. Order: 3° > 2° > 1° (for alkyl migration aptitude).',
  'Molality': 'A concept related to Molality. Refer to your textbook for the specific formula or definition.',
  'Molecular Formula': 'A concept related to Molecular Formula. Refer to your textbook for the specific formula or definition.',
  'Molecular Geometry': '3D shape of molecule from VSEPR: linear, bent, trigonal planar, tetrahedral, trigonal pyramidal, trigonal bipyramidal, octahedral, square planar. Lone pairs reduce bond angles.',
  'Molecular Shape': 'Determined by hybridisation and lone pairs. sp: linear; sp²: trigonal planar; sp³: tetrahedral; sp³d: trigonal bipyramidal; sp³d²: octahedral. Lone pairs occupy equatorial positions in TBP.',
  'Molecular Speed Distribution': 'Maxwell-Boltzmann distribution. Most probable speed < mean speed < RMS speed. Distribution broadens at higher T. Fraction of molecules with speed > threshold increases exponentially with T.',
  'Multinomial Coefficients': 'A concept related to Multinomial Coefficients. Refer to your textbook for the specific formula or definition.',
  'Multinomial Theorem': 'A concept related to Multinomial Theorem. Refer to your textbook for the specific formula or definition.',
  'Mutual Inductance': 'M: EMF induced in secondary = M·dI₁/dt. M depends on geometry and media. For two coils: M = k√(L₁L₂) where k = coupling factor (0 to 1). Unit: Henry.',
  'NOₓ': 'Nitrogen oxides: NO, NO₂, N₂O. NO: colourless, from combustion/lightning. NO₂: brown, toxic. N₂O: laughing gas. All contribute to atmospheric pollution. Standard: <0.1 ppm (NO₂) for air quality.',
  'NOₓ Chemistry': 'NO and NO₂ from combustion (N₂ + O₂ → 2NO at high T). NO₂ brown gas, paramagnetic. 2NO₂ ⇌ N₂O₄. In atmosphere: contribute to smog and acid rain. Catalytic converter: 2NO → N₂ + O₂.',
  'Nitroalkanes': 'R−NO₂. Weak acids (α-H more acidic due to −I of NO₂). Reduction: NO₂ → NHOH → NH₂. Tautomerism: nitro ⇌ aci-nitro. Victor Meyer test distinguishes primary (red), secondary (blue), tertiary (colourless).',
  'Nitrogen Cycle': 'A concept related to Nitrogen Cycle. Refer to your textbook for the specific formula or definition.',
  'Nitronium Ion': 'A concept related to Nitronium Ion. Refer to your textbook for the specific formula or definition.',
  'Normal Distribution': 'Bell-shaped symmetric distribution. Defined by μ (mean) and σ (standard deviation). 68-95-99.7 rule: 68% within 1σ, 95% within 2σ. Standard normal Z = (X−μ)/σ.',
  'Normal to Plane': 'A concept related to Normal to Plane. Refer to your textbook for the specific formula or definition.',
  'Normality': 'A concept related to Normality. Refer to your textbook for the specific formula or definition.',
  'Optimization': 'Finding maximum or minimum of function. Set f\'(x) = 0, find critical points, test by second derivative (f\'\'>0: min, f\'\'<0: max). Constrained optimization uses Lagrange multipliers.',
  'Optimization Problems': 'A concept related to Optimization Problems. Refer to your textbook for the specific formula or definition.',
  'Orbital Velocity': 'v₀ = √(GM/r) = √(gR²/r). At Earth\'s surface ≈ 7.9 km/s. v₀ = vₑ/√2. Geostationary orbit: T = 24h, r ≈ 36,000 km. Satellite in lower orbit: faster.',
  'Ore Beneficiation': 'Physical concentration of ore before smelting. Methods: crushing/grinding, gravity separation (dense media), froth flotation (sulfides), magnetic separation (iron ores), electrostatic separation.',
  'Oxidizing Agents': 'Substances that cause oxidation (gain electrons themselves). Strength: F₂ > O₃ > Cl₂ > Br₂ > I₂. KMnO₄, K₂Cr₂O₇, HNO₃ (conc.), H₂SO₄ (conc.), H₂O₂ also important oxidising agents.',
  'Oxidizing Power': 'Tendency to gain electrons (be reduced). Measured by standard reduction potential E°. Higher E° = stronger oxidizing agent. F₂ (E°=+2.87V) > Cl₂ > Br₂ > I₂.',
  'Oxime Formation': 'A concept related to Oxime Formation. Refer to your textbook for the specific formula or definition.',
  'Packing Efficiency': 'A concept related to Packing Efficiency. Refer to your textbook for the specific formula or definition.',
  'Pair of Lines': 'Combined equation ax²+2hxy+by² = 0 represents pair through origin. Slopes m₁,m₂: m₁+m₂ = −2h/b, m₁m₂ = a/b. Angle between: tanθ = 2√(h²−ab)/(a+b). Coincident if h²=ab.',
  'Parametric Curves': 'Curve defined by x=f(t), y=g(t). dy/dx = (dy/dt)/(dx/dt). d²y/dx² = [d/dt(dy/dx)]/(dx/dt). Arc length = ∫√((dx/dt)²+(dy/dt)²)dt.',
  'Pascal\'s Triangle': 'Triangular array of binomial coefficients. (n,k)th entry = C(n,k). Each entry = sum of two above. Row n: coefficients in (a+b)ⁿ expansion. Properties: symmetric, C(n,r) + C(n,r+1) = C(n+1,r+1).',
  'Peracid Reactions': 'Reactions using peroxy acids (R−CO−O−OH). mCPBA: epoxidation of alkenes (stereospecific, syn), Baeyer-Villiger oxidation of ketones to esters/lactones. Nucleophilic oxygen transfer.',
  'Percentage Error': 'A concept related to Percentage Error. Refer to your textbook for the specific formula or definition.',
  'Phenol Reactions': 'A concept related to Phenol Reactions. Refer to your textbook for the specific formula or definition.',
  'Phenol Synthesis': 'From benzene diazonium salt (warm water). Cumene process (industrial): PhCH(CH₃)₂ → PhC(CH₃)₂OOH → Ph-OH + CH₃COCH₃. Dow process: chlorobenzene + NaOH (600°C, high pressure).',
  'Physical Properties of Water': 'Bp: 100°C (high due to H-bonding). Fp: 0°C. Density max at 4°C (ice less dense than water). High surface tension (72 mN/m), specific heat (4.18 J/g·K), dielectric constant (80).',
  'Planes in 3D': 'A concept related to Planes in 3D. Refer to your textbook for the specific formula or definition.',
  'Point Defects': 'Schottky: equal cation+anion vacancies, density decreases. Frenkel: ion moves to interstitial site, density unchanged. F-centre: anion vacancy trapping electron, causes colour. Impurity defects in doped semiconductors.',
  'Polyester': 'A concept related to Polyester. Refer to your textbook for the specific formula or definition.',
  'Position Vector': 'Vector from origin to point. If origin O and point P, position vector = OP⃗. Midpoint of AB = (a⃗+b⃗)/2. Centroid of triangle = (a⃗+b⃗+c⃗)/3.',
  'Potential Energy': 'A concept related to Potential Energy. Refer to your textbook for the specific formula or definition.',
  'Power': 'P = W/t = Fv = τω. Average power = W/t. Instantaneous power P = F⃗·v⃗. Electrical power P = VI = I²R = V²/R. Units: Watt (J/s).',
  'Power Dissipation': 'P = I²R = V²/R = VI. Heat generated in resistor. In AC: P = V_rms × I_rms × cosφ. For pure resistor in AC: P = ½V₀I₀. Power factor cosφ = 1 (resistive), 0 (purely reactive).',
  'Power Set': 'P(A) = set of all subsets of A. If |A| = n, |P(A)| = 2ⁿ. P(∅) = {∅}. P({a,b}) = {∅,{a},{b},{a,b}}. Power set always has more elements than original set.',
  'Power of Mirror': 'P = 1/f (in metres) = 2/R. Concave mirror: positive P. Convex mirror: negative P (virtual focus). Mirror power treated like lens power in optics calculations.',
  'Power of a Point': 'For circle: if line through P cuts circle at A,B: PA·PB = constant = PT² (T = tangent point). Positive (outside circle) = PT². Negative (inside) = −|PA·PB|. Radical axis: equal power w.r.t. two circles.',
  'Precipitation': 'Formation of insoluble solid from solution when ionic product > Ksp. Selective precipitation: adjust ion concentration to precipitate one ion while other stays in solution. Used in qualitative analysis.',
  'Precipitation Reactions': 'Reaction forming insoluble precipitate. BaCl₂ + Na₂SO₄ → BaSO₄↓ + 2NaCl. AgNO₃ + NaCl → AgCl↓. Used in gravimetric analysis, water treatment, qualitative analysis.',
  'Primary Amine Synthesis': 'A concept related to Primary Amine Synthesis. Refer to your textbook for the specific formula or definition.',
  'Protein Denaturation': 'Disruption of secondary/tertiary/quaternary structure without breaking peptide bonds. Causes: heat, extreme pH, organic solvents, heavy metals. Reversible (renaturation) or irreversible.',
  'Protein Synthesis': 'mRNA sequence (codons) read by ribosome. tRNA anticodon binds codon, delivers amino acid. Peptide bond formation between amino acids. Elongation, termination, post-translational modification.',
  'Purification Methods': 'Filtration, distillation, crystallisation, sublimation, zone refining (semiconductors), electrorefining (Cu), chromatography, extraction. Choice depends on nature of impurity and product.',
  'RC Circuit': 'A concept related to RC Circuit. Refer to your textbook for the specific formula or definition.',
  'Rainbow Formation': 'Sunlight enters water droplet, undergoes refraction + TIR + refraction. Different wavelengths refracted by different angles (dispersion). Primary rainbow: 40-42°. Secondary: 51-54° (colours reversed).',
  'Rancidity': 'Deterioration of fats/oils by oxidation (rancidity) or hydrolysis. Free radicals attack unsaturated C=C. Prevented by antioxidants (BHA, BHT, Vitamin E), inert gas packaging, refrigeration.',
  'Rare Events': 'Events with very low probability but in large number of trials. Modelled by Poisson distribution (limiting case of binomial: n→∞, p→0, np=λ). Examples: radioactive decay, bacterial mutations.',
  'Rational Functions': 'f(x) = P(x)/Q(x). Domain: x where Q(x)≠0. Partial fractions used for integration. Asymptotes: vertical (Q=0), horizontal (degree comparison), oblique (degree P = degree Q+1).',
  'Receptors': 'Biological molecules (usually proteins) that bind specific drugs/hormones. Agonists: activate receptor. Antagonists: block receptor without activating. Lock-and-key or induced-fit mechanism.',
  'Rectangular Hyperbola': 'xy = c². Asymptotes: x and y axes. Eccentricity e = √2. Parametric: (ct, c/t). For equilateral hyperbola a = b, so asymptotes perpendicular. Rectangular hyperbola: same shape regardless of rotation.',
  'Rectifier Circuit': 'Converts AC to DC. Half-wave: single diode, only positive half cycle. Full-wave bridge: 4 diodes, both half cycles. Ripple factor (HW) = 1.21; (FW) = 0.48. Filtered with capacitor.',
  'Refining of Iron': 'Pig iron (4% C) → steel by removing C, Si, S, P, Mn. Basic oxygen process (BOF): O₂ blown into molten pig iron. Open hearth furnace. Electric arc furnace for specialty steels.',
  'Refractive Index': 'n = c/v = sin(θᵢ)/sin(θᵣ) (Snell\'s law, from medium 1 to 2). n = c/v where v is speed in medium. For glass ≈ 1.5. Relates to wavelength: smaller λ → higher n. Dispersion.',
  'Resolving Power': 'Ability to distinguish two closely spaced objects. Telescope: RP = D/1.22λ. Microscope: RP = 2μsinθ/λ. Diffraction grating: RP = nN. Smaller wavelength and larger aperture → better resolution.',
  'Rolling Motion': 'A concept related to Rolling Motion. Refer to your textbook for the specific formula or definition.',
  'Roots of Unity': 'A concept related to Roots of Unity. Refer to your textbook for the specific formula or definition.',
  'Rubber': 'A concept related to Rubber. Refer to your textbook for the specific formula or definition.',
  'Rydberg Formula': '1/λ = RZ²(1/n₁² − 1/n₂²). R_H = 1.097×10⁷ m⁻¹. Lyman: n₁=1 (UV). Balmer: n₁=2 (visible). Paschen: n₁=3 (IR). Brackett: n₁=4. Pfund: n₁=5.',
  'SN1 Mechanism': 'Step 1 (slow, RDS): RX ionises to R⁺ + X⁻. Step 2 (fast): Nu attacks planar carbocation from both faces. Results in racemisation. Favoured by 3°, benzylic, allylic substrates and polar protic solvents.',
  'SN1/SN2': 'SN1: unimolecular, via carbocation, 1st order, racemisation, 3° > 2° > 1°. SN2: bimolecular, backside attack, 2nd order, inversion, 1° > 2° (3° impossible). Polar aprotic favours SN2.',
  'SN2 Mechanism': 'One-step: Nu attacks C from back face as LG leaves. Bimolecular TS. Complete inversion of configuration (Walden inversion). Favoured by 1°, strong nucleophile, polar aprotic solvent (DMSO, acetone).',
  'SN2 Reaction': 'Backside attack of nucleophile on sp³ carbon bearing leaving group. Rate = k[substrate][nucleophile]. Inversion of configuration. Hindered substrates (3°) don\'t react by SN2 (steric). Best with 1° halides.',
  'SO₂ Chemistry': 'SO₂: bent molecule, sp³, bond order 1.5 (resonance). Acidic anhydride of H₂SO₃. Bleaching agent (reduction, reversible). Air pollutant from burning sulfur-containing fuels. Contact process intermediate.',
  'Sandmeyer Reaction': 'ArN₂⁺ + Cu₂X₂/HX (X = Cl, Br) → ArX. Also: ArN₂⁺ + CuCN → ArCN; + Cu₂O/H₂O → ArOH. Balz-Schiemann: ArN₂⁺BF₄⁻ →Δ ArF + BF₃ + N₂. Used to introduce halide/CN into aromatic ring.',
  'Second Law': 'Entropy of universe never decreases: ΔS_universe ≥ 0. Heat flows spontaneously from hot to cold. No engine can be 100% efficient. Sets direction of spontaneous processes.',
  'Selective Precipitation': 'Adding reagent to precipitate one ion while another remains in solution. Controlled by Ksp values and concentration. Add S²⁻ at low pH → precipitate CuS (small Ksp), ZnS stays dissolved (larger Ksp).',
  'Sequences': 'A concept related to Sequences. Refer to your textbook for the specific formula or definition.',
  'Set Operations': 'Union A∪B, Intersection A∩B, Difference A−B, Complement A\'. Cartesian product A×B = {(a,b): a∈A, b∈B}. |A×B| = |A|×|B|. A⊂B iff A∩B = A iff A∪B = B.',
  'Shielding': 'Reduction of effective nuclear charge by inner electrons. σ: shielding constant from Slater\'s rules. Z_eff = Z − σ. 4f electrons poor shielders (leads to lanthanide contraction).',
  'Sigma Notation': 'Σᵢ xᵢ = x₁+x₂+...+xₙ. Properties: Σ(aᵢ+bᵢ) = Σaᵢ+Σbᵢ; Σcaᵢ = cΣaᵢ. Telescoping sum: Σ(f(i+1)−f(i)) = f(n+1)−f(1). Key formulae: Σi = n(n+1)/2, Σi² = n(n+1)(2n+1)/6.',
  'Signum Function': 'sgn(x) = 1 (x>0), 0 (x=0), −1 (x<0). Discontinuous at x=0. |x| = x·sgn(x). d/dx(|x|) = sgn(x) for x≠0. Used in piecewise function analysis.',
  'Skew Lines': 'Lines in 3D that are neither parallel nor intersecting. Shortest distance = |( a⃗₂−a⃗₁)·(b⃗₁×b⃗₂)|/|b⃗₁×b⃗₂|. Skew lines always exist in 3D but not in 2D.',
  'Solenoid Field': 'B = μ₀nI (n = turns per unit length) inside solenoid. Uniform field inside. Field outside ≈ 0 (infinite solenoid). Toroid: B = μ₀NI/2πr (only inside toroid).',
  'Solvay Process': 'Industrial manufacture of Na₂CO₃. NaCl + NH₃ + CO₂ + H₂O → NaHCO₃ (precipitates due to low solubility) → Na₂CO₃ + H₂O + CO₂. NH₃ recycled via Ca(OH)₂. Efficient and widely used.',
  'Solvent Effects': 'Polar protic (water, ROH): stabilises ions by H-bonding, favours SN1, E1; retards SN2. Polar aprotic (DMSO, DMF, acetone): solvates cation not anion, enhances nucleophilicity of anion, favours SN2.',
  'Spin State': 'High spin: weak field ligands, unpaired electrons fill eg before pairing. Low spin: strong field ligands, electrons pair in t₂g first. Depends on pairing energy vs Δ. Affects magnetism and reactivity.',
  'Spontaneity': 'ΔG < 0: spontaneous at constant T, P. ΔG = 0: equilibrium. ΔG > 0: non-spontaneous. Spontaneous ≠ fast. ΔG depends on both ΔH and TΔS. ΔS_universe > 0 for spontaneous process.',
  'States of Matter': 'Solid: definite shape/volume, high density, incompressible. Liquid: definite volume, no fixed shape. Gas: no fixed shape/volume, compressible. Plasma: ionised gas. Phase transitions driven by T and P.',
  'Steel Making': 'Iron + oxygen process to reduce carbon content. Basic oxygen furnace (BOF): blows O₂ into molten pig iron, reduces C to 0.1−1%. Alloying: Cr (stainless), Ni (tough), W (tool steel), Mn (hard).',
  'Stereochemistry': '3D arrangement of atoms in molecules. Includes: constitutional isomers, geometric (cis/trans), optical (enantiomers, diastereomers), conformational isomers. Determines physical properties and biological activity.',
  'Stratospheric Chemistry': 'Ozone layer (15-35 km): absorbs UV-B (280-320 nm). Chapman cycle: O₂ →hν 2O•; O•+O₂→O₃; O₃→hν O₂+O•. Depleted by CFCs via Cl• chain. Antarctic ozone hole each winter.',
  'Structure Elucidation': 'Determining molecular structure from analytical data: MS (molar mass), IR (functional groups), ¹H NMR (H environments, integration, coupling), ¹³C NMR, UV-Vis (conjugation), elemental analysis.',
  'Substitution at α-C': 'α-carbon is carbon adjacent to C=O. More acidic due to resonance stabilisation of enolate. Reactions: halogenation, aldol, Claisen, Michael. HVZ reaction: α-bromination of carboxylic acid via acid bromide.',
  'Sulfonamide': 'R−SO₂−NH₂ or R−SO₂−NHR\'. Formed by amine + benzenesulfonyl chloride (Hinsberg test). First sulpha drugs. 1° sulfonamide (N−H): acidic, soluble in NaOH. 2° sulfonamide: neutral, insoluble.',
  'Sum to Product': 'A concept related to Sum to Product. Refer to your textbook for the specific formula or definition.',
  'System of Equations': 'Linear system: unique solution (det≠0), infinite solutions (rank<n), no solution (rank(A)≠rank(A|b)). Cramer\'s rule, Gaussian elimination, matrix inverse methods. Homogeneous: always has trivial solution.',
  'Telescope': 'Astronomical telescope: objective (large fo) + eyepiece (short fe). Magnification m = fo/fe. Length = fo + fe. Resolving power = D/1.22λ. Reflecting: concave mirror as objective (no chromatic aberration).',
  'Tishchenko Reaction': 'Aldehyde (no α-H) disproportionation with Al(OEt)₃ catalyst: 2RCHO → RCOOCH₂R (ester). Milder conditions than Cannizzaro. Used industrially for ethyl acetate from acetaldehyde.',
  'Titration Curves': 'Plot of pH vs volume of titrant added. Equivalence point: stoichiometric completion. Strong-strong: equivalence pH=7. Weak acid-strong base: pH>7. Buffer region: pH ≈ pKa. Inflection point = equivalence.',
  'Toroid': 'Donut-shaped solenoid. B = μ₀NI/2πr (r = radius to point). B = 0 outside toroid. Used as inductor in electronics to avoid stray field. More efficient than solenoid for AC circuits.',
  'Total Internal Reflection': 'Complete reflection at interface when angle > critical angle (θ_c = sin⁻¹(n₂/n₁), n₁>n₂). Applications: optical fibre, prism binoculars, endoscopy, diamond brilliance.',
  'Total Probability': 'A concept related to Total Probability. Refer to your textbook for the specific formula or definition.',
  'Total Probability Theorem': 'A concept related to Total Probability Theorem. Refer to your textbook for the specific formula or definition.',
  'Toxicology': 'A concept related to Toxicology. Refer to your textbook for the specific formula or definition.',
  'Trajectory Equation': 'A concept related to Trajectory Equation. Refer to your textbook for the specific formula or definition.',
  'Triple Product': 'A concept related to Triple Product. Refer to your textbook for the specific formula or definition.',
  'UV-Visible Spectroscopy': 'A concept related to UV-Visible Spectroscopy. Refer to your textbook for the specific formula or definition.',
  'Vapour Pressure': 'A concept related to Vapour Pressure. Refer to your textbook for the specific formula or definition.',
  'Venn Diagrams': 'A concept related to Venn Diagrams. Refer to your textbook for the specific formula or definition.',
  'Void Analysis': 'A concept related to Void Analysis. Refer to your textbook for the specific formula or definition.',
  'Wagner-Meerwein': 'A concept related to Wagner-Meerwein. Refer to your textbook for the specific formula or definition.',
  'Wallis Formula': 'A concept related to Wallis Formula. Refer to your textbook for the specific formula or definition.',
  'Wave Equation': '∂²y/∂t² = v²∂²y/∂x². General solution: y = f(x−vt) + g(x+vt). For EM waves: v = c = 1/√(μ₀ε₀). Speed depends on medium properties.',
  'Wave Optics': 'A concept related to Wave Optics. Refer to your textbook for the specific formula or definition.',
  'Wave-Particle Duality': 'Quantum objects exhibit both wave and particle properties. Light: photoelectric effect (particle), diffraction (wave). Electrons: double-slit diffraction (wave), photoelectric-type detection (particle). Complementarity principle.',
  'Wavelength-Frequency': 'c = fλ for EM waves. E = hf = hc/λ (photon energy). In medium: v = fλ. When light slows in medium, frequency unchanged, wavelength decreases. λ = v/f.',
  'Wheatstone Bridge': 'Circuit to measure unknown resistance. At balance: P/Q = R/S (galvanometer reads zero). Metre bridge: special case using uniform wire. Sensitivity maximum when all arms approximately equal.',
  'Wien\'s Displacement Law': 'A concept related to Wien\'s Displacement Law. Refer to your textbook for the specific formula or definition.',
  'Wittig Reaction': 'A concept related to Wittig Reaction. Refer to your textbook for the specific formula or definition.',
  'Work Done': 'A concept related to Work Done. Refer to your textbook for the specific formula or definition.',
  'Work Function': 'φ: minimum energy to remove electron from metal surface. KE_max = hf − φ. φ depends on metal (Cs: 1.9 eV, Na: 2.3 eV, Cu: 4.7 eV). Higher φ: higher threshold frequency for photoelectric effect.',
  'X-ray Diffraction': 'A concept related to X-ray Diffraction. Refer to your textbook for the specific formula or definition.',
  'YDSE': 'Young\'s Double Slit Experiment. Fringe width β = λD/d. Path difference: Δ = yd/D (for small angles). Maxima: Δ = nλ; Minima: Δ = (2n−1)λ/2. Intensity I = 4I₀cos²(πΔ/λ). Needs coherent sources.',
  'Z_eff': 'Effective nuclear charge. Z_eff = Z − σ (σ = shielding constant). Determines atomic radius, ionisation energy, electronegativity. Increases across period (electrons added to same shell don\'t shield well).',
  'Zero Error': 'Instrumental error when reading is non-zero with no measurement. Positive zero error: zero of vernier ahead of main scale. Negative: behind. Subtract zero error from all readings for correction.',
  'Zero-Point Energy': 'Minimum energy of quantum system at absolute zero: E₀ = ½hν (for harmonic oscillator). Cannot be zero due to Heisenberg uncertainty (Δx·Δp ≥ ℏ/2). Explains He remaining liquid at 0 K under 1 atm.',
  'd-d Transitions': 'Electronic transitions between d-orbitals split by crystal field. Absorb visible light. Energy of transition = crystal field splitting Δ. Selection rules: spin-allowed and Laporte. Basis for colour of TM complexes.',
  'pH Calculations': 'A concept related to pH Calculations. Refer to your textbook for the specific formula or definition.',
  'pH Definition': 'A concept related to pH Definition. Refer to your textbook for the specific formula or definition.',
  'pH Measurement': 'A concept related to pH Measurement. Refer to your textbook for the specific formula or definition.',
  'pKa': 'A concept related to pKa. Refer to your textbook for the specific formula or definition.',
  'pKb': 'A concept related to pKb. Refer to your textbook for the specific formula or definition.',
};